spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: jwt-backend-integrate
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_test_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: myverysecurejwtsecretkey1234567890123456789012

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
